// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddNote'](arg1, arg2, arg3);
}

export function AnswerEscalation(arg1, arg2) {
  return window['go']['main']['App']['AnswerEscalation'](arg1, arg2);
}

export function CreateSession(arg1, arg2) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetAgentEvents(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAgentEvents'](arg1, arg2, arg3);
}

export function GetAttachment(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAttachment'](arg1, arg2, arg3);
}

export function GetRateLimit() {
  return window['go']['main']['App']['GetRateLimit']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function InterruptSession(arg1) {
  return window['go']['main']['App']['InterruptSession'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function ResumeSession(arg1) {
  return window['go']['main']['App']['ResumeSession'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function UpdateNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3, arg4);
}
