// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddNote'](arg1, arg2, arg3);
}

export function AddScopedNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddScopedNote'](arg1, arg2, arg3, arg4);
}

export function AnswerEscalation(arg1, arg2) {
  return window['go']['main']['App']['AnswerEscalation'](arg1, arg2);
}

export function ClipboardImage() {
  return window['go']['main']['App']['ClipboardImage']();
}

export function CompactSession(arg1) {
  return window['go']['main']['App']['CompactSession'](arg1);
}

export function CreateSession(arg1, arg2) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2);
}

export function CreateSessionWithProvider(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSessionWithProvider'](arg1, arg2, arg3, arg4);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function FinishAgent(arg1) {
  return window['go']['main']['App']['FinishAgent'](arg1);
}

export function GetAgentEventTail(arg1, arg2) {
  return window['go']['main']['App']['GetAgentEventTail'](arg1, arg2);
}

export function GetAgentEvents(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAgentEvents'](arg1, arg2, arg3);
}

export function GetAttachment(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAttachment'](arg1, arg2, arg3);
}

export function GetChanges(arg1, arg2) {
  return window['go']['main']['App']['GetChanges'](arg1, arg2);
}

export function GetFileDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFileDiff'](arg1, arg2, arg3);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetRateLimit() {
  return window['go']['main']['App']['GetRateLimit']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function InterruptSession(arg1) {
  return window['go']['main']['App']['InterruptSession'](arg1);
}

export function ListOpenEscalations() {
  return window['go']['main']['App']['ListOpenEscalations']();
}

export function ListRepos(arg1) {
  return window['go']['main']['App']['ListRepos'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListUserPlugins() {
  return window['go']['main']['App']['ListUserPlugins']();
}

export function MessageAgent(arg1, arg2) {
  return window['go']['main']['App']['MessageAgent'](arg1, arg2);
}

export function PauseAgent(arg1) {
  return window['go']['main']['App']['PauseAgent'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function RestartAgent(arg1) {
  return window['go']['main']['App']['RestartAgent'](arg1);
}

export function ResumeAgent(arg1) {
  return window['go']['main']['App']['ResumeAgent'](arg1);
}

export function ResumeSession(arg1) {
  return window['go']['main']['App']['ResumeSession'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SetSessionConfig(arg1, arg2) {
  return window['go']['main']['App']['SetSessionConfig'](arg1, arg2);
}

export function SetSessionMode(arg1, arg2) {
  return window['go']['main']['App']['SetSessionMode'](arg1, arg2);
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function TerminalClose(arg1) {
  return window['go']['main']['App']['TerminalClose'](arg1);
}

export function TerminalOpen(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalOpen'](arg1, arg2, arg3);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TerminalWrite(arg1, arg2) {
  return window['go']['main']['App']['TerminalWrite'](arg1, arg2);
}

export function UpdateNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3, arg4);
}
