// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {notes} from '../models';
import {main} from '../models';

export function AddNote(arg1:number,arg2:string,arg3:string):Promise<notes.Note>;

export function AnswerEscalation(arg1:number,arg2:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string):Promise<notes.Session>;

export function GetAgentEvents(arg1:number,arg2:number,arg3:number):Promise<Array<notes.AgentEvent>>;

export function GetSession(arg1:number):Promise<main.SessionSnapshot>;

export function ListSessions():Promise<Array<notes.Session>>;

export function PickDirectory():Promise<string>;

export function SendMessage(arg1:number,arg2:string):Promise<void>;

export function StopSession(arg1:number):Promise<void>;

export function UpdateNote(arg1:number,arg2:number,arg3:string,arg4:string):Promise<notes.Note>;
